### PR TITLE
fixing text input

### PR DESCRIPTION
**Pull request by skamp91**
now the text input will be cleared immediately.

### CODE REVIEW

**Comment by skamp91** [comment]
why is it invalid?

**Review by Code-Recursion — COMMENTED** [review]
Please provide live version/screenshots and provide a brief explination to make this PR to be merged

**Comment by Code-Recursion** [comment]
Use #20 fixed in commit message if you want to consider this in hacktoberfest

**Comment by skamp91** [comment]
ok, I understood.
I have no Domain where I can broadcast the live-version...and when I take screenshots, you don't see anything, because the input field will deleted immediately.
I am pretty new in open-source, please have understanding with me :)

**Comment by Code-Recursion** [comment]
@skamp91  don't worry if you are new to open source, 
To publish or host any site you can use github pages
To activate github pages click on the settings of the repository which you want to host
Swipe down you will find an option to turn on github pages click on it then you will see your site live and share that link here so that i can review,  i hope it helped :)

**Comment by Code-Recursion** [comment]
2u

**Comment by Code-Recursion** [comment]
@skamp91  don't worry if you are new to open source, 
To publish or host any site you can use github pages
To activate github pages click on the settings of the repository which you want to host
Swipe down you will find an option to turn on github pages click on it then you will see your site live and share that link here so that i can review,  i hope it helped :)

**Comment by skamp91** [comment]
@Code-Recursion ah ok thank you very much, and now I have to add a new file with screens and the share-link or is it better to adjust the README.md
Github Pages is really cool. 
I do it in the afternoon :)

**Comment by Code-Recursion** [comment]
No just send me the link in comment while explaining what have you done

**Comment by skamp91** [comment]
Now I have another problem, I enabled github pages for my cloned repo and changed the hyperlink to my Repo, but when I click on "View live Version" the old, your version of calculator is called. How can I activate my new script.js?

**Comment by skamp91** [comment]
[https://skamp91.github.io/UI-Calculator](https://skamp91.github.io/UI-Calculator)
This the link for the live view.

I added a js function which read the input values from all letters and sets it to an empty string.
_Known Issues_: 
- if you press a letter the complete input field will be deleted

**Pull request closed without merging**
