### PR TITLE
Fixed invalid operations

### PR DESCRIPTION
**Pull request by MatheusMuriel**
I fixed not only division by 0, i fixed all invalid operations like "158***" (arithmetics errors)

### CODE REVIEW

**Comment by MatheusMuriel** [comment]
Issue: #3

**Comment by Code-Recursion** [comment]
@MatheusMuriel please resolve the conflicts to make ur PR merged

**Comment by MatheusMuriel** [comment]
@Code-Recursion Hello, Resolved, thaks for attention

**Comment by Code-Recursion** [comment]
@MatheusMuriel please publish it on gh-pages and then send the url for testing purpose, also describe what have been changed.

**Comment by MatheusMuriel** [comment]
You edited the comment but i already recorded the video: https://drive.google.com/file/d/1Mir5GyHcQQjPVOhmKkQj2uLtTgwmQZt9/view
But now i'll publish on gh-pages and send you the link

**Comment by MatheusMuriel** [comment]
[gh-pages for test](https://matheusmuriel.github.io/UI-Calculator/)

In JavaScript the ```eval()``` executes the string as a JavaScript code, so it returns ```Infinity```, why JavaScript is one of the only programming languages that accepts division by 0.  
To check this you can execute this code:
```js
let test = 15/0;
console.log(test);
// The output will be >>> Infinit
```
So if you run eval with an invalid code it will return an error.
```js 
eval('15********8');
// The output will be >>> Thrown: SyntaxError: Unexpected token **
```


So I created an empty variable to store the result and execute the ```eval``` inside of a ```try catch```
```js
let result;
try {
  result = eval(operation);  
} catch (error) {}
```

In JavaScript if you convert a ```undefied``` variable or ```0``` in a ```Boolean``` he will return ```false```. But he return ```true``` if you pass ```Infinity```, because of that i put some validations in the ```if``` so that if the result is 0 or a non-infinite number and is not undefined it displays the result, else it says that the operation was invalid.

```js
if ( result === 0 || isFinite(result) && Boolean(result) ) {
    document.getElementById('display').value = result;
  } else {
    document.getElementById('display').value = 'Invalid operation';
  }
```

Wow! I hope this explanation was enough for you accept my PR. hahaha

Thanks for attention and Happy Hacktoberfest!

**Comment by MatheusMuriel** [comment]
@Code-Recursion   
[gh-pages for test](https://matheusmuriel.github.io/UI-Calculator/)

In JavaScript the ```eval()``` executes the string as a JavaScript code, so it returns ```Infinity```, why JavaScript is one of the only programming languages that accepts division by 0.  
To check this you can execute this code:
```js
let test = 15/0;
console.log(test);
// The output will be >>> Infinit
```
So if you run eval with an invalid code it will return an error.
```js 
eval('15********8');
// The output will be >>> Thrown: SyntaxError: Unexpected token **
```


So I created an empty variable to store the result and execute the ```eval``` inside of a ```try catch```
```js
let result;
try {
  result = eval(operation);  
} catch (error) {}
```

In JavaScript if you convert a ```undefied``` variable or ```0``` in a ```Boolean``` he will return ```false```. But he return ```true``` if you pass ```Infinity```, because of that i put some validations in the ```if``` so that if the result is 0 or a non-infinite number and is not undefined it displays the result, else it says that the operation was invalid.

```js
if ( result === 0 || isFinite(result) && Boolean(result) ) {
    document.getElementById('display').value = result;
  } else {
    document.getElementById('display').value = 'Invalid operation';
  }
```

Wow! I hope this explanation was enough for you accept my PR. hahaha

Thanks for attention and Happy Hacktoberfest!

**Comment by Code-Recursion** [comment]
@MatheusMuriel  it was a great explaination, and amazing work by you
Yeah this is more then enough for this PR XD

**Review by Code-Recursion — APPROVED** [review]
Amazing work @MatheusMuriel

**Pull request merged**
