### PR TITLE
Made responsive on mobile screen

### PR DESCRIPTION
**Pull request by 1880akshay**

### CODE REVIEW

**Review by Code-Recursion — APPROVED** [review]
Thaknks for the PR @1880akshay please also provide Screen shots and mention what is fixed by seeing the code it is hard to see live changes kindly send the screen shots and explain what you have fixed.

**Review by Code-Recursion — CHANGES_REQUESTED** [review]
more work needed

**Comment by 1880akshay** [comment]
Hey @Code-Recursion , I have set the margin, padding and overflow-x properties of the html and body tags accordingly to hide the horizontal scrollbar on small screen devices. Further, I have decreased the width of the main container from 360 to 340 px to support almost every mobile device without clipping. Also, the calculator is now center aligned properly. I am attaching some screenshots for your reference. Also, if any more changes are required, do let me know!
Screen Shot 2020-10-01 at 09 09 16
Screen Shot 2020-10-01 at 09 08 14

**Review by Code-Recursion — APPROVED** [review]
thanks for the PR @1880akshay

**Pull request merged**
