### PR TITLE
fixed hovering issues

### PR DESCRIPTION
**Pull request by DevanshCodes**
fixes issue #14

### CODE REVIEW

**Comment by Code-Recursion** [comment]
Please provide screen shots and also explain what you have changed

**Comment by DevanshCodes** [comment]
Hey this is the recorded video of this working: https://www.loom.com/share/37604d03771448deb27465d7818bb049. Now what I changed:
I disabled any pointer interaction for the disabled button. Hence, on hovering on the disabled button it will not change the position of 0 button.

**Comment by DevanshCodes** [comment]
@Code-Recursion any other change is needed or is it good to go?

**Comment by Code-Recursion** [comment]
@DevanshCodes  good work thanks for The PR

**Comment by DevanshCodes** [comment]
If it's fine, can you merge it, please?

**Comment by DevanshCodes** [comment]
@Code-Recursion can it be merged?

**Comment by Code-Recursion** [comment]
Yeah sure, great work! Keep it up
Thanks for the PR

**Review by Code-Recursion — APPROVED** [review]
Awesome work

**Pull request merged**
